### ISSUE TITLE
yourIdToken is apple id or apple login token ? 

### ISSUE THREAD

**Issue by mfaizan1** [stefan-prokop-cz/verify-apple-id-token#1]
I am little confused with naming will this verify 
`yourIdToken` or `apple id` ?

**Comment by stefan-prokop-cz** [comment]
Thanks for question! It will verify your identity token (`idToken`). Here is official apple documentation about verifying users (https://developer.apple.com/documentation/sign_in_with_apple/sign_in_with_apple_rest_api/verifying_a_user).

Not all of the steps from `Verify the Identity Token` chapter are implemented yet. If you want, you can open a PR.

**Comment by stefan-prokop-cz** [comment]
Here I created the issue https://github.com/stefan-prokop-cz/verify-apple-id-token/issues/2
