### ISSUE TITLE
Can't use it in ES5 based NodeJS express apps

### ISSUE THREAD

**Issue by shehrozsheikh** [stefan-prokop-cz/verify-apple-id-token#5]
I tried using 

`const {verifyAppleToken} = require('verify-apple-id-token');`  and
`const verifyAppleToken = require('verify-apple-id-token'); `

both in my ExpressJS app where import statement doesn't work, it returns this error:

`"TypeError: VerifyAppleIdTokenParams is not a function"`

so I was wondering if I can use this library in ES5 based Node App?

**Comment by stefan-prokop-cz** [comment]
Hello @shehrozsheikh

there are two functions which are exported from this module. First one is called `getApplePublicKey` - I think it's not important now. The second one is the `default` and that is function you are looking for. So try this: `const verifyAppleToken = require('verify-apple-id-token').default;` and then you can continue like this `verifyAppleToken({ ... })` ([see usage](https://github.com/stefan-prokop-cz/verify-apple-id-token#usage))

Let me know if its working :slightly_smiling_face:

**Comment by shehrozsheikh** [comment]
Hi @stefan-prokop-cz it worked for me, Thank you!
